"""
Utility functions and constants for RamSim.
"""

from .constants import (
    RAM_USAGE_INDEX,
    CPU_USAGE_INDEX,
    PAGE_FAULTS_INDEX,
    SWAP_USAGE_INDEX,
    POWER_INDEX,
    STATE_RUNNING,
    STATE_SUSPENDED,
    STATE_SWAPPED,
    STATE_KILLED,
    ACTION_KILL,
    ACTION_SWAP_OUT,
    ACTION_SWAP_IN,
    ACTION_SUSPEND,
    ACTION_RESUME,
    ACTION_RENICE_INCREASE,
    ACTION_RENICE_DECREASE,
    ACTION_NOOP
)

__all__ = [
    'RAM_USAGE_INDEX',
    'CPU_USAGE_INDEX',
    'PAGE_FAULTS_INDEX',
    'SWAP_USAGE_INDEX',
    'POWER_INDEX',
    'STATE_RUNNING',
    'STATE_SUSPENDED',
    'STATE_SWAPPED',
    'STATE_KILLED',
    'ACTION_KILL',
    'ACTION_SWAP_OUT',
    'ACTION_SWAP_IN',
    'ACTION_SUSPEND',
    'ACTION_RESUME',
    'ACTION_RENICE_INCREASE',
    'ACTION_RENICE_DECREASE',
    'ACTION_NOOP'
]
