"""
Constants used throughout the RamSim environment.
"""

# System stats indices
RAM_USAGE_INDEX = 0
CPU_USAGE_INDEX = 1
PAGE_FAULTS_INDEX = 2
SWAP_USAGE_INDEX = 3
POWER_INDEX = 4

# Process state values
STATE_RUNNING = 1.0
STATE_SUSPENDED = 0.6
STATE_SWAPPED = 0.3
STATE_KILLED = 0.0

# Action indices
ACTION_KILL = 0
ACTION_SWAP_OUT = 1
ACTION_SWAP_IN = 2
ACTION_SUSPEND = 3
ACTION_RESUME = 4
ACTION_RENICE_INCREASE = 5
ACTION_RENICE_DECREASE = 6
ACTION_NOOP = 7
